/////////////////////////////////////////////////////////////////////////////////////////////////
// Change History Form1.Designer.cs
// Date        Developer     Description
// ----------  ------------  ----------------------------------------------------
// 01/27/2026  JADANIE       Auto-generated by Visual Studio Form Designer; initial
//                           calculator UI layout created to mirror Windows calculator devices,
//                           including display, button grid, and form sizing.
// 02/03/2026  JADANIE       Verified control layout and event hookups in the Form Designer.
// 02/05/2026  JADANIE       Renamed tableLayoutPanel1 to mainLayoutPanel to improve
//                           identifier clarity and readability.
// 02/06/2026  JADANIE       Polished UI styling (spacing, colors) and improved display behavior
//                           (no-wrap, MaxLength, horizontal scrolling); added custom form/app icon (.ico).
/////////////////////////////////////////////////////////////////////////////////////////////////

namespace LCalc
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// this is the initilization of the components of the form
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.mainLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.equalsBtn = new System.Windows.Forms.Button();
            this.decimalPtBtn = new System.Windows.Forms.Button();
            this.num0Btn = new System.Windows.Forms.Button();
            this.posNegBtn = new System.Windows.Forms.Button();
            this.minusBtn = new System.Windows.Forms.Button();
            this.num3Btn = new System.Windows.Forms.Button();
            this.num2Btn = new System.Windows.Forms.Button();
            this.num1Btn = new System.Windows.Forms.Button();
            this.num6Btn = new System.Windows.Forms.Button();
            this.num5Btn = new System.Windows.Forms.Button();
            this.num4Btn = new System.Windows.Forms.Button();
            this.multBtn = new System.Windows.Forms.Button();
            this.num8Btn = new System.Windows.Forms.Button();
            this.clearAllBtn = new System.Windows.Forms.Button();
            this.display = new System.Windows.Forms.TextBox();
            this.divBtn = new System.Windows.Forms.Button();
            this.backBtn = new System.Windows.Forms.Button();
            this.plusBtn = new System.Windows.Forms.Button();
            this.clearEntryBtn = new System.Windows.Forms.Button();
            this.num7Btn = new System.Windows.Forms.Button();
            this.num9Btn = new System.Windows.Forms.Button();
            this.mainLayoutPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // mainLayoutPanel
            // 
            this.mainLayoutPanel.ColumnCount = 4;
            this.mainLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayoutPanel.Controls.Add(this.equalsBtn, 3, 5);
            this.mainLayoutPanel.Controls.Add(this.decimalPtBtn, 2, 5);
            this.mainLayoutPanel.Controls.Add(this.num0Btn, 1, 5);
            this.mainLayoutPanel.Controls.Add(this.posNegBtn, 0, 5);
            this.mainLayoutPanel.Controls.Add(this.minusBtn, 3, 3);
            this.mainLayoutPanel.Controls.Add(this.num3Btn, 2, 4);
            this.mainLayoutPanel.Controls.Add(this.num2Btn, 1, 4);
            this.mainLayoutPanel.Controls.Add(this.num1Btn, 0, 4);
            this.mainLayoutPanel.Controls.Add(this.num6Btn, 2, 3);
            this.mainLayoutPanel.Controls.Add(this.num5Btn, 1, 3);
            this.mainLayoutPanel.Controls.Add(this.num4Btn, 0, 3);
            this.mainLayoutPanel.Controls.Add(this.multBtn, 3, 2);
            this.mainLayoutPanel.Controls.Add(this.num8Btn, 1, 2);
            this.mainLayoutPanel.Controls.Add(this.clearAllBtn, 1, 1);
            this.mainLayoutPanel.Controls.Add(this.display, 0, 0);
            this.mainLayoutPanel.Controls.Add(this.divBtn, 3, 1);
            this.mainLayoutPanel.Controls.Add(this.backBtn, 2, 1);
            this.mainLayoutPanel.Controls.Add(this.plusBtn, 3, 4);
            this.mainLayoutPanel.Controls.Add(this.clearEntryBtn, 0, 1);
            this.mainLayoutPanel.Controls.Add(this.num7Btn, 0, 2);
            this.mainLayoutPanel.Controls.Add(this.num9Btn, 2, 2);
            this.mainLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainLayoutPanel.GrowStyle = System.Windows.Forms.TableLayoutPanelGrowStyle.FixedSize;
            this.mainLayoutPanel.Location = new System.Drawing.Point(10, 10);
            this.mainLayoutPanel.Name = "mainLayoutPanel";
            this.mainLayoutPanel.Padding = new System.Windows.Forms.Padding(5);
            this.mainLayoutPanel.RowCount = 6;
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.mainLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.mainLayoutPanel.Size = new System.Drawing.Size(452, 551);
            this.mainLayoutPanel.TabIndex = 0;
            // 
            // equalsBtn
            // 
            this.equalsBtn.BackColor = System.Drawing.Color.LightSteelBlue;
            this.equalsBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.equalsBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.equalsBtn.ForeColor = System.Drawing.Color.Black;
            this.equalsBtn.Location = new System.Drawing.Point(338, 456);
            this.equalsBtn.Name = "equalsBtn";
            this.equalsBtn.Size = new System.Drawing.Size(106, 87);
            this.equalsBtn.TabIndex = 20;
            this.equalsBtn.Text = "=";
            this.equalsBtn.UseVisualStyleBackColor = false;
            this.equalsBtn.Click += new System.EventHandler(this.equalsBtn_Click);
            // 
            // decimalPtBtn
            // 
            this.decimalPtBtn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.decimalPtBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decimalPtBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 39.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.decimalPtBtn.Location = new System.Drawing.Point(228, 456);
            this.decimalPtBtn.Name = "decimalPtBtn";
            this.decimalPtBtn.Size = new System.Drawing.Size(104, 87);
            this.decimalPtBtn.TabIndex = 19;
            this.decimalPtBtn.Text = ".";
            this.decimalPtBtn.UseVisualStyleBackColor = false;
            this.decimalPtBtn.Click += new System.EventHandler(this.decimalPtBtn_Click);
            // 
            // num0Btn
            // 
            this.num0Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num0Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num0Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num0Btn.Location = new System.Drawing.Point(118, 456);
            this.num0Btn.Name = "num0Btn";
            this.num0Btn.Size = new System.Drawing.Size(104, 87);
            this.num0Btn.TabIndex = 18;
            this.num0Btn.Text = "0";
            this.num0Btn.UseVisualStyleBackColor = false;
            this.num0Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // posNegBtn
            // 
            this.posNegBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.posNegBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.posNegBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.posNegBtn.ForeColor = System.Drawing.Color.Black;
            this.posNegBtn.Location = new System.Drawing.Point(8, 456);
            this.posNegBtn.Name = "posNegBtn";
            this.posNegBtn.Size = new System.Drawing.Size(104, 87);
            this.posNegBtn.TabIndex = 17;
            this.posNegBtn.Text = "+/-";
            this.posNegBtn.UseVisualStyleBackColor = false;
            this.posNegBtn.Click += new System.EventHandler(this.posNegBtn_Click);
            // 
            // minusBtn
            // 
            this.minusBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.minusBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.minusBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 39.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.minusBtn.ForeColor = System.Drawing.Color.Black;
            this.minusBtn.Location = new System.Drawing.Point(338, 272);
            this.minusBtn.Name = "minusBtn";
            this.minusBtn.Size = new System.Drawing.Size(106, 86);
            this.minusBtn.TabIndex = 16;
            this.minusBtn.Text = "-";
            this.minusBtn.UseVisualStyleBackColor = false;
            this.minusBtn.Click += new System.EventHandler(this.minusBtn_Click);
            // 
            // num3Btn
            // 
            this.num3Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num3Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num3Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num3Btn.Location = new System.Drawing.Point(228, 364);
            this.num3Btn.Name = "num3Btn";
            this.num3Btn.Size = new System.Drawing.Size(104, 86);
            this.num3Btn.TabIndex = 15;
            this.num3Btn.Text = "3";
            this.num3Btn.UseVisualStyleBackColor = false;
            this.num3Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num2Btn
            // 
            this.num2Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num2Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num2Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num2Btn.Location = new System.Drawing.Point(118, 364);
            this.num2Btn.Name = "num2Btn";
            this.num2Btn.Size = new System.Drawing.Size(104, 86);
            this.num2Btn.TabIndex = 14;
            this.num2Btn.Text = "2";
            this.num2Btn.UseVisualStyleBackColor = false;
            this.num2Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num1Btn
            // 
            this.num1Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num1Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num1Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num1Btn.Location = new System.Drawing.Point(8, 364);
            this.num1Btn.Name = "num1Btn";
            this.num1Btn.Size = new System.Drawing.Size(104, 86);
            this.num1Btn.TabIndex = 13;
            this.num1Btn.Text = "1";
            this.num1Btn.UseVisualStyleBackColor = false;
            this.num1Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num6Btn
            // 
            this.num6Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num6Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num6Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num6Btn.Location = new System.Drawing.Point(228, 272);
            this.num6Btn.Name = "num6Btn";
            this.num6Btn.Size = new System.Drawing.Size(104, 86);
            this.num6Btn.TabIndex = 11;
            this.num6Btn.Text = "6";
            this.num6Btn.UseVisualStyleBackColor = false;
            this.num6Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num5Btn
            // 
            this.num5Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num5Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num5Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num5Btn.Location = new System.Drawing.Point(118, 272);
            this.num5Btn.Name = "num5Btn";
            this.num5Btn.Size = new System.Drawing.Size(104, 86);
            this.num5Btn.TabIndex = 10;
            this.num5Btn.Text = "5";
            this.num5Btn.UseVisualStyleBackColor = false;
            this.num5Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num4Btn
            // 
            this.num4Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num4Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num4Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num4Btn.Location = new System.Drawing.Point(8, 272);
            this.num4Btn.Name = "num4Btn";
            this.num4Btn.Size = new System.Drawing.Size(104, 86);
            this.num4Btn.TabIndex = 9;
            this.num4Btn.Text = "4";
            this.num4Btn.UseVisualStyleBackColor = false;
            this.num4Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // multBtn
            // 
            this.multBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.multBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.multBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.multBtn.ForeColor = System.Drawing.Color.Black;
            this.multBtn.Location = new System.Drawing.Point(338, 180);
            this.multBtn.Name = "multBtn";
            this.multBtn.Size = new System.Drawing.Size(106, 86);
            this.multBtn.TabIndex = 8;
            this.multBtn.Text = "x";
            this.multBtn.UseVisualStyleBackColor = false;
            this.multBtn.Click += new System.EventHandler(this.multBtn_Click);
            // 
            // num8Btn
            // 
            this.num8Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num8Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num8Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num8Btn.Location = new System.Drawing.Point(118, 180);
            this.num8Btn.Name = "num8Btn";
            this.num8Btn.Size = new System.Drawing.Size(104, 86);
            this.num8Btn.TabIndex = 6;
            this.num8Btn.Text = "8";
            this.num8Btn.UseVisualStyleBackColor = false;
            this.num8Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // clearAllBtn
            // 
            this.clearAllBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.clearAllBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.clearAllBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.clearAllBtn.Location = new System.Drawing.Point(118, 88);
            this.clearAllBtn.Name = "clearAllBtn";
            this.clearAllBtn.Size = new System.Drawing.Size(104, 86);
            this.clearAllBtn.TabIndex = 2;
            this.clearAllBtn.Text = "C";
            this.clearAllBtn.UseVisualStyleBackColor = false;
            this.clearAllBtn.Click += new System.EventHandler(this.clearAllBtn_Click);
            // 
            // display
            // 
            this.display.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.mainLayoutPanel.SetColumnSpan(this.display, 4);
            this.display.Cursor = System.Windows.Forms.Cursors.Default;
            this.display.Dock = System.Windows.Forms.DockStyle.Fill;
            this.display.Font = new System.Drawing.Font("Microsoft Sans Serif", 39.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.display.Location = new System.Drawing.Point(8, 8);
            this.display.MaxLength = 100;
            this.display.Name = "display";
            this.display.ReadOnly = true;
            this.display.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.display.ShortcutsEnabled = false;
            this.display.Size = new System.Drawing.Size(436, 60);
            this.display.TabIndex = 0;
            this.display.TabStop = false;
            this.display.Text = "0";
            this.display.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.display.WordWrap = false;
            // 
            // divBtn
            // 
            this.divBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.divBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.divBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.divBtn.ForeColor = System.Drawing.Color.Black;
            this.divBtn.Location = new System.Drawing.Point(338, 88);
            this.divBtn.Name = "divBtn";
            this.divBtn.Size = new System.Drawing.Size(106, 86);
            this.divBtn.TabIndex = 4;
            this.divBtn.Text = "/";
            this.divBtn.UseVisualStyleBackColor = false;
            this.divBtn.Click += new System.EventHandler(this.divBtn_Click);
            // 
            // backBtn
            // 
            this.backBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.backBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.backBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backBtn.Location = new System.Drawing.Point(228, 88);
            this.backBtn.Name = "backBtn";
            this.backBtn.Size = new System.Drawing.Size(104, 86);
            this.backBtn.TabIndex = 3;
            this.backBtn.Text = "<<";
            this.backBtn.UseVisualStyleBackColor = false;
            this.backBtn.Click += new System.EventHandler(this.backBtn_Click);
            // 
            // plusBtn
            // 
            this.plusBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.plusBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.plusBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.plusBtn.ForeColor = System.Drawing.Color.Black;
            this.plusBtn.Location = new System.Drawing.Point(338, 364);
            this.plusBtn.Name = "plusBtn";
            this.plusBtn.Size = new System.Drawing.Size(106, 86);
            this.plusBtn.TabIndex = 12;
            this.plusBtn.Text = "+";
            this.plusBtn.UseVisualStyleBackColor = false;
            this.plusBtn.Click += new System.EventHandler(this.plusBtn_Click);
            // 
            // clearEntryBtn
            // 
            this.clearEntryBtn.BackColor = System.Drawing.Color.Gainsboro;
            this.clearEntryBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.clearEntryBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.clearEntryBtn.Location = new System.Drawing.Point(8, 88);
            this.clearEntryBtn.Name = "clearEntryBtn";
            this.clearEntryBtn.Size = new System.Drawing.Size(104, 86);
            this.clearEntryBtn.TabIndex = 1;
            this.clearEntryBtn.Text = "CE";
            this.clearEntryBtn.UseVisualStyleBackColor = false;
            this.clearEntryBtn.Click += new System.EventHandler(this.clearEntryBtn_Click);
            // 
            // num7Btn
            // 
            this.num7Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num7Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num7Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num7Btn.Location = new System.Drawing.Point(8, 180);
            this.num7Btn.Name = "num7Btn";
            this.num7Btn.Size = new System.Drawing.Size(104, 86);
            this.num7Btn.TabIndex = 5;
            this.num7Btn.Text = "7";
            this.num7Btn.UseVisualStyleBackColor = false;
            this.num7Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // num9Btn
            // 
            this.num9Btn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.num9Btn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.num9Btn.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.num9Btn.Location = new System.Drawing.Point(228, 180);
            this.num9Btn.Name = "num9Btn";
            this.num9Btn.Size = new System.Drawing.Size(104, 86);
            this.num9Btn.TabIndex = 7;
            this.num9Btn.Text = "9";
            this.num9Btn.UseVisualStyleBackColor = false;
            this.num9Btn.Click += new System.EventHandler(this.numBtn_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightGray;
            this.ClientSize = new System.Drawing.Size(472, 571);
            this.Controls.Add(this.mainLayoutPanel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(480, 600);
            this.Name = "Form1";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tinfo-200 Calculator";
            this.mainLayoutPanel.ResumeLayout(false);
            this.mainLayoutPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel mainLayoutPanel;
        private System.Windows.Forms.TextBox display;
        private System.Windows.Forms.Button clearEntryBtn;
        private System.Windows.Forms.Button equalsBtn;
        private System.Windows.Forms.Button num0Btn;
        private System.Windows.Forms.Button posNegBtn;
        private System.Windows.Forms.Button minusBtn;
        private System.Windows.Forms.Button num3Btn;
        private System.Windows.Forms.Button num2Btn;
        private System.Windows.Forms.Button num1Btn;
        private System.Windows.Forms.Button plusBtn;
        private System.Windows.Forms.Button num6Btn;
        private System.Windows.Forms.Button num5Btn;
        private System.Windows.Forms.Button num4Btn;
        private System.Windows.Forms.Button multBtn;
        private System.Windows.Forms.Button num9Btn;
        private System.Windows.Forms.Button num8Btn;
        private System.Windows.Forms.Button num7Btn;
        private System.Windows.Forms.Button divBtn;
        private System.Windows.Forms.Button backBtn;
        private System.Windows.Forms.Button clearAllBtn;
        private System.Windows.Forms.Button decimalPtBtn;
    }
}

