///////////////////////////////////////////////////////////////////////////////////////////
// Change History Program.cs
// Date        Developer     Description
// ----------  ------------  ----------------------------------------------------
// 01/27/2026  JADANIE       Program entry point auto-generated by Visual Studio;
//                           no additional logic changes made.
// 02/06/2026  JADANIE       Added a high level documentation describing application
//                           startup flow and calculator behavior for clarity and
//                           maintainability. No functional changes made.
// 02/06/2026  JADANIE       Reviewed program entry point; no functional changes required.
//////////////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

////////////////////////////////////////////////////////////////////////////////////////////
// How the Calculator Works (High-Level Overview):
// - The application launches Form1 using Application.Run().
// - All calculator behavior is handled through button click event handlers.
// - Each button triggers an event method that updates internal state and display.
// - Arithmetic operations are performed when the Equals button is pressed.
// - Errors (e.g., divide by zero) are handled gracefully with user notification and reset.
//
// See Form1.cs for core calculator logic and state management.
////////////////////////////////////////////////////////////////////////////////////////////

namespace LCalc
{
    internal static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }
    }
}
